### ISSUE TITLE
Mission 1 Brightness

### ISSUE THREAD

**Issue by thomasdowding** [Meorge/sneaksters-testing#12]
The screen brightness on the first level (for me anyway) seems to be a bit dark as I'm finding it difficult to see which is just leading to me getting a bit disoriented. I haven't tried the other levels yet so this may an issue across the game or maybe there's something wrong on my end.

**Comment by thomasdowding** [comment]
![image](https://user-images.githubusercontent.com/55148125/64625914-e46f1480-d3e4-11e9-9b68-6abbc8a769e0.png)

**Comment by Meorge** [comment]
There's nothing in different levels that should cause different brightnesses, so this would be an issue with all of the levels. Shouldn't be a very difficult fix, though!

**Comment by Meorge** [comment]
I've brightened the ambient light in levels from 0.29 to 0.35. Not a huge bump, since the areas are supposed to be somewhat dark and disorienting, but hopefully enough to not make it as annoyingly so.
