### ISSUE TITLE
[Solved]Game crashed on main menu

### ISSUE THREAD

**Issue by murphymUrph21** [Meorge/sneaksters-testing#124]
when I press right mouse button click on main menu the UI almost completes its animation to where I have options to click and then it crashes. this was the windows version. I have windows 10 installed

**Comment by Meorge** [comment]
Can you send your player log? They should be at `C:\Users\username\AppData\LocalLow\ZenithPoint\Sneaksters\Player.log`. There shouldn't be any personal information in it, but it may be a good idea to check it beforehand to delete anything private, just in case.

**Comment by murphymUrph21** [comment]
Here it is, hope it helps. Your hella smart if your able to debug using this log! Checked it seems fine. Im impressed your game connects with discord though, it mentioned it in the log.

Sent from Mail for Windows 10

**Comment by murphymUrph21** [comment]
[Player-prev.log](https://github.com/Meorge/sneaksters-testing/files/5206028/Player-prev.log)
[Player.log](https://github.com/Meorge/sneaksters-testing/files/5206029/Player.log)
Here is the logs

**Comment by murphymUrph21** [comment]
Don't press the Right mouse button or application will close. Press Enter
