### ISSUE TITLE
Add “Press Enter” button prompt for title screen

### ISSUE THREAD

**Issue by Meorge** [Meorge/sneaksters-testing#125]
Inspired by a previous issue (#124) where a user didn't know how to get to the main menu - the solution is not obvious but it should be. Adding a button prompt will fix this issue

**Comment by Meorge** [comment]
Rudimentary prompt is in. For v0.3.2 I may want to redesign the title screen to be a bit cleaner

**Comment by patataofcourse** [comment]
This still says "Oprime cualquier botón" (Press any button) in the Spanish translation, so I guess it's something that should also be changed in the translation files

**Comment by Meorge** [comment]
Yep, I am going to have to request updated translations soon

**Comment by Meorge** [comment]
"Press Enter" prompt now has some animations and stuff so I'm going to close this issue! (Translations aren't super high priority at the moment, and since I'm *hoping* to add new stuff soon, I think I'll wait until after that to work on updated translations.)
