### ISSUE TITLE
Crystal spawned in wall

### ISSUE THREAD

**Issue by ZeldaPlayer29** [Meorge/sneaksters-testing#13]
Didn't manage to catch a screenshot of this and it hasn't happened since but one of the crystals spawned inside the wall.

Highlighted on the image below (this image was taken on a different session so the player location, number of gems held etc don't match up).

![image](https://user-images.githubusercontent.com/55148125/64626692-23ea3080-d3e6-11e9-8fc3-95bd04683c7a.png)

**Comment by Meorge** [comment]
That's quite a strange bug. Did you pick up the Gemstone and drop it at all before it spawned into the wall? It should, in theory, fall a distance and then respawn in the correct location...

**Comment by thomasdowding** [comment]
Nope, it spawned there that one time automatically. Haven't been able to replicate it so not sure what could be causing it.

**Comment by Meorge** [comment]
I've not seen this issue occur and a lot has changed since September 2019 so I'm closing this for now
