### ISSUE TITLE
[Linux] Unnecessary "[Keyboard]" showing up

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#133]
Playing 0.3.1 Linux build through a Manjaro Linux 20.0.3 live USB.
"[Keyboard]" shows up after mentions of keys.
![image](https://user-images.githubusercontent.com/29714419/93522479-cf9b5a00-f931-11ea-8ca5-02ee4d50acce.png)
In some cases, this goes out of the screen.
![image](https://user-images.githubusercontent.com/29714419/93522629-112c0500-f932-11ea-8478-a26b507eb51f.png)

**Comment by ZeldaPlayer29** [comment]
I just saw that this issue was opened. It also happens on Windows v0.3.1 - I referenced it here https://github.com/Meorge/sneaksters-testing/issues/141

**Comment by Meorge** [comment]
I'm 99% sure I know why this is happening, and it's really stupid. Essentially, I think the keyboard strings are different on macOS from Windows or Linux (for example, Linux and Windows call the Enter key "Return", while macOS literally just calls it the hexadecimal character `0x0D`, which is a carriage return.)

Just to confirm, though, could you try opening the build at https://github.com/Meorge/sneaksters-testing/releases/tag/v0.3.1.1-prealpha and sending me the `Player.log` file?

**Comment by Meorge** [comment]
This does indeed appear to be what's going on. I'll try making a build that attempts to fix this issue for at least Return and Escape (but I don't know how many other keys use different strings on different platforms).

**Comment by Meorge** [comment]
It looks like the test fix works (when I can spell the things right, at least). Hopefully Unity will get their stuff together and make the strings the same across platforms, but until then I'll just have to allow multiple strings to point to a single display string.

**Comment by Meorge** [comment]
It's fixed for now for v0.3.2, but only for the strings that I'm aware have changed (Enter/Return and Escape). There may well be other strings that change across platforms, but I don't know what they are so I'll just have to add them once they come up.

**Comment by ZeldaPlayer29** [comment]
[Player.log](https://github.com/Meorge/sneaksters-testing/files/5299950/Player.log)
Sorry Meorge, I somehow missed this (maybe because patata opened it not me). I've ran the build and attached the log, just in case it helps.

**Comment by Meorge** [comment]
Thanks! It looks like Windows uses "ENTER [Keyboard]" instead of "Enter [Keyboard]" or "Return [Keyboard]" so I've added it to the list as well.
