### ISSUE TITLE
Language selection screen issues

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#136]
French = Polish?
![image](https://user-images.githubusercontent.com/29714419/93525480-65d17f00-f936-11ea-82ea-b049d6be1fb5.png)
(Choosing French changes to Polish)

What happens if you select the currently chosen language
![image](https://user-images.githubusercontent.com/29714419/93525624-a204df80-f936-11ea-9202-ef434c75d687.png)

**Comment by patataofcourse** [comment]
Besides, there's a little globe icon in the bottom right corner (which I'm guessing leads to this page, since it disappeared after choosing a language) which does nothing.

**Comment by Meorge** [comment]
The globe icon indicates that you're connected to the server. The other issues are weird, will look into them

**Comment by Meorge** [comment]
Fixed the issue with the Polish flag, and probably the double-check issue as well. (Both languages used the identifier `pl`, so when the current language was set to `pl` they apparently both thought they were enabled, on top of them using the same flag icon asset.)

**Comment by Meorge** [comment]
The ability to select the already-selected language and go to an empty menu has been fixed in v0.3.2 as well.
