### ISSUE TITLE
No mouse sensitivity setting

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#137]
(Linux 0.3.1, Manjaro 20.0.3 live USB)
The mouse sensitivity is too much, and a small nudge moves the camera by a considerable angle. There's no option to change this in Settings.

**Comment by Meorge** [comment]
Just implemented the setting control for mouse sensitivity and its use in game without doing any testing, how could this possibly go wrong

**Comment by Meorge** [comment]
Looks like I forgot an argument that made the game refuse to compile, but after that it seems to be working. You can multiply the current mouse sensitivity by a value between 0 and 2 in v0.3.2
