### ISSUE TITLE
Volume resets when opening the game

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#138]
(Linux build 0.3.1, Manjaro 20.0.3 live USB)
The volume returns to the default of 50% when opening the game, even though it shows the setting correctly on the Settings page.
![image](https://user-images.githubusercontent.com/29714419/93526743-299f1e00-f938-11ea-8a8f-4ac3cedf9f4d.png)
Both music and SFX.
Doesn't happen when resetting via language change.

**Comment by Meorge** [comment]
Should be fixed in v0.3.2
