### ISSUE TITLE
Spanish text wraps around too often

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#139]
Greatest example:
![image](https://user-images.githubusercontent.com/29714419/93527586-60296880-f939-11ea-97b0-1ccc421608fb.png)

In this case, changing the text itself is enough, but in others, it's better to let the text have more space, for example:
![image](https://user-images.githubusercontent.com/29714419/93527811-b39bb680-f939-11ea-94bd-9a8d403fa073.png)

**Comment by Meorge** [comment]
Wrapping is enabled on TextMeshPro objects by default; I'll go through and disable it. Thanks!

**Comment by Meorge** [comment]
Wrapping has been disabled on a bunch of the text objects in v0.3.2. There may be a few weird bugs to fix but it shouldn't be too bad.
