### ISSUE TITLE
Mission 1 - Spawned holding crystal

### ISSUE THREAD

**Issue by thomasdowding** [Meorge/sneaksters-testing#14]
After playing Mission 1 multiple times and failing each time, I spawned holding one of the crystals (which didn't happen on the previous attempts).

![image](https://user-images.githubusercontent.com/55148125/64628219-e76c0400-d3e8-11e9-807d-6e76bb7ca057.png)

**Comment by Meorge** [comment]
While it's hard to say for certain, I think this *may* have been to do with the fact that the Thief was spawned at the origin and then moved to the spawn point. Perhaps they happened to intersect with the gemstone, somehow, and thus pick it up? Given we haven't seen it more, I'm going to close it - but we can reopen it if necessary.
