### ISSUE TITLE
Two columns of menu items

### ISSUE THREAD

**Issue by ZeldaPlayer29** [Meorge/sneaksters-testing#141]
Windows Version 0.3.1
![image](https://user-images.githubusercontent.com/55148125/93873150-20f87000-fcc9-11ea-839d-99f371d89c01.png)

See the image I uploaded. ESC [Keyboard] / Right-Click icon doesn't fit into the button properly (is "[Keyboard]" supposed to be there?)

Also, the game didn't correctly detect my resolution when I first launched it (my monitor is 1920x1080, my Windows resolution is 1920x1080 but the game defaulted to 1024x576). Once I corrected this, the game remembered my settings and this did not need correcting on subsequent runs.

In the screenshot, the two column menu glitch that I seem to recall happening with the credits is happening again. One of the side effects of this is that it was impossible to change the quality level.

Edit - actually, I think the resolution problem is because I wasn't running the game in fullscreen and a 1920x1080 window would just fill the screen, defeating the purpose of being windowed. However, when I changed to fullscreen the resolution stayed the same - maybe it could be changed to automatically detect the highest resolution possible when switching to fullscreen?

**Comment by Meorge** [comment]
As you noted, the "[Keyboard]" bug is something that's already known about, but it's good to know it also happens on Windows.

In this report, what I'm really confused about is the two-column glitch. Are you able to reproduce it, and if so, what steps do you take to reproduce it? The menu items should only be split into two columns once you activate the credits, and then they should return to one column once you leave the credits. If it continues to be a problem, I might just remove the whole two-columns-for-credits thing and have it always stay as one column.

**Comment by ZeldaPlayer29** [comment]
I've been trying to reproduce this for a while but unfortunately, I just can't get it to happen again. It is probably related to the credits being split into two columns, but I'm not sure what could of caused. I discovered another problem related to the credits when I was trying to reproduce this, but I'll create a new issue for that.

**Comment by Meorge** [comment]
I'd never seen this bug before, so I can't say with certainty that this fix will work, but I went through and set the column count to 1 in a few more places, which should *hopefully* take care of the issue for v0.3.2. I'm going to close it for now, and if it comes up again (and we're able to reproduce it) we can re-open it.
