### ISSUE TITLE
Entering the languages menu prevents the credits from playing

### ISSUE THREAD

**Issue by ZeldaPlayer29** [Meorge/sneaksters-testing#144]
Windows 0.3.1

I'm not sure what causes this, but if you enter the languages menu, go back and try to view the credits they don't progress any more - they instead just hang at Project Lead. The game is not completely frozen as you can still go back. This issue still persists even after entering and playing a game - the only way I could find to fix it is to change the language (possibly because changing the language resets the game?)

This issue happens regardless of which language the game is set to.

**Comment by Meorge** [comment]
Credits have been removed in v0.3.2, so this shouldn't be an issue anymore :P They are now in the README for this repo instead
