### ISSUE TITLE
Multiple menus not having "Back" buttons

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#16]
It feels weird having to choose the job when you misclicked the Make a Squad button. Would rather have one added.

**Comment by patataofcourse** [comment]
Same applies for the mission choosing menu, you may want to go back and check on the squad.

**Comment by patataofcourse** [comment]
Accidentally closed, whoops

**Comment by Meorge** [comment]
If you misclick on the "Make a Squad" button, you can choose a job and then exit out via the "Back" button in the lower left corner. I think it'd be a really good (and probably easy) idea to move the "Back" button up, though, so it can be accessed at all points. Thank you for the suggestion!

**Comment by Meorge** [comment]
Fixed!
