### ISSUE TITLE
Game starts at incorrect/broken size 

### ISSUE THREAD

**Issue by insert-usernamehere** [Meorge/sneaksters-testing#163]
When opening the game on a windows laptop that's at 1920 x 1080 resolution 125% zoom the game starts at a size too big to be playable
![image](https://user-images.githubusercontent.com/29443173/96353570-46478680-109b-11eb-9181-a665c483546e.png)

**Comment by Meorge** [comment]
When you refer to "125% zoom", you mean that you've set things in Windows accessibility settings to be 125% the normal size?

**Comment by insert-usernamehere** [comment]
No by default every window computer applies a zoom to your display to make things easier to read you can find this setting in windows setting -> system -> display

**Comment by Meorge** [comment]
Hmmm okay, I will see if it's possible for me to use actual screen height/width in order to determine the starting resolution. In the meantime, you should be able to navigate into Settings -> Resolution & Quality -> Resolution to make it a size that fits the screen.

**Comment by Meorge** [comment]
Alternatively I may have the game default to full-screen

**Comment by Meorge** [comment]
Looking at this again, I think the resolution was correct. The game window is barely bigger than the screen - in fact, it looks like it may be precisely the size of the screen, but the title bar at the top of the game window pushes the bottom down underneath the taskbar.

As a fix, the game will now default to full-screen on first launch.
