### ISSUE TITLE
People still appear as if in they were in the squad once they left

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#17]
This has also caused the same person being in the squad menu twice

**Comment by Meorge** [comment]
I think I've seen this bug a fair amount. My hope is to do a revamp of the squad room screen, so I'm not sure if I'll be trying to fix this specific bug or just tear the whole thing down and redo it.

**Comment by patataofcourse** [comment]
Has this been fixed? I think I saw it working properly, but it may be due to the other person being stuck in a buggy "Connecting to server" after finishing a game.

**Comment by Meorge** [comment]
Since the squad screen has been redesigned, I'm going to close this for now and we can reopen this issue or open a new one if it pops back up again
