### ISSUE TITLE
0.4.0 Windows - file missing the .exe extension?

### ISSUE THREAD

**Issue by ZeldaPlayer29** [Meorge/sneaksters-testing#178]
When I downloaded version 0.4.0 for Windows, the Sneaksters.exe file appeared to be missing the ".exe" extension. This meant that the file could not be opened without renaming the file to add the .exe extension. Should be an easy fix, but thought I would mention in case it goes unnoticed.

**Comment by Meorge** [comment]
Thanks for submitting! I think others reported this issue a while back but to the best of my memory we never actually created an issue for it. For v0.4.1 I'll make sure the exe extension is added.

**Comment by Meorge** [comment]
I've been manually doing this fix for v0.4.1 and v0.4.2, but for v0.4.3 onwards it should be done automatically.
