### ISSUE TITLE
0.4.0 Windows 10 - Level Select screen input options

### ISSUE THREAD

**Issue by ZeldaPlayer29** [Meorge/sneaksters-testing#179]
When on the Level Select screen, levels 1, 2 and 3 cannot be selected by clicking the mouse, only levels 4 and 5 can. All levels on the screen can be selected using the keyboard. All other menu options outside of this screen seem to be fine using the mouse. I imagine this is an easy fix, probably just a mouse click event trigger missing on the buttons for levels 1, 2 and 3.

**Comment by Meorge** [comment]
I'm planning on redoing the level select screen, as the one that's currently in was rushed so I could get v0.2.0(?) out the door ASAP. It's good to know there's even more reason for me to work on the newer version, though! :P It'll probably come with v0.4.2 or perhaps a bit later.

**Comment by Meorge** [comment]
Closing, since the redesigned level select is now an issue of its own (#184)
