### ISSUE TITLE
Only one reticle for UI main menu buttons

### ISSUE THREAD

**Issue by Meorge** [Meorge/sneaksters-testing#183]
Currently, every single UI main menu button has an animated reticle attached to it, that's animating at all times. Only the reticle for the currently-selected item is made visible.

It shouldn't be too hard to get rid of this, and instead have there be a single reticle object that has its position shifted to whatever the currently selected item is. This should improve performance.

**Comment by Meorge** [comment]
There are still some minor issues with it, but this is mostly implemented so I'm going to close it for now. Maybe if people complain about the minor issues I'll work more to fix them, but it's possible they'll just irk me and no one else.

**Comment by ZeldaPlayer29** [comment]
> There are still some minor issues with it, but this is mostly implemented so I'm going to close it for now. Maybe if people complain about the minor issues I'll work more to fix them, but it's possible they'll just irk me and no one else.

I'm going to have to playtest again at some point - though it might be worth mentioning, as I have high-functioning autism, I tend to notice the little things a lot, so any complaints about minor issues from me probably won't reflect on what other people think as a whole.
