### ISSUE TITLE
Flashing gem in squad screen

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#19]
See here for a gif of it happening.
https://gyazo.com/bebcb8ecffaa98117d4ac5a866c4abb3
This was on Windows, first build in this repo, with two instances of it running.

**Comment by Meorge** [comment]
I've seen this bug once or twice before, I think - it's a very strange one. Should be a pretty easy fix; just need to make Gemstones check what state the game is in (menus vs gameplay) and destroy themselves if the former.

**Comment by Meorge** [comment]
Just implemented the fix. I'm going to close this for now, but if the issue persists in later builds we can re-open it.
