### ISSUE TITLE
Changing language sometimes leaves to bugged "choose a job" screen

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#21]
The room has 0 members, no code and no leader.
![imagen](https://user-images.githubusercontent.com/29714419/64660388-5aed3000-d440-11e9-9596-5a35203c1189.png)
![imagen](https://user-images.githubusercontent.com/29714419/64660413-75270e00-d440-11e9-8579-b0ba63107a10.png)

**Comment by Meorge** [comment]
That's definitely a new one.

Could you send your log file? Were there any out-of-place errors?

**Comment by patataofcourse** [comment]
Uh, I was actually running the game twice, but it has happened to me with only one client.
And, uh, when trying to make a squad from the other window, this happened:
![imagen](https://user-images.githubusercontent.com/29714419/64660480-c8995c00-d440-11e9-94a3-c902399be7f5.png)

**Comment by patataofcourse** [comment]
Actually, nevermind. It was the same one.

**Comment by Meorge** [comment]
I think I'll need more information in order to diagnose and fix this bug.

**Comment by Meorge** [comment]
I may have figured out this bug for v0.1.7. Going to close it until we see it pop up again.
