### ISSUE TITLE
Doors sometimes don't work

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#25]
This is a known bug in the Discord server, have gotten it working with two instances on the game in one PC:
![imagen](https://user-images.githubusercontent.com/29714419/64662142-a6efa300-d447-11e9-9a90-29cc313b4e4b.png)

![imagen](https://user-images.githubusercontent.com/29714419/64662131-9fc89500-d447-11e9-9ffd-d4a6c697768f.png)

**Comment by Meorge** [comment]
The "error" code in your second screenshot actually looks like it's suggesting it received the door-toggle RPC correctly, which is especially strange. Did the door's status never change on the Thief end during this play session?

**Comment by patataofcourse** [comment]
The door never closed or opened, no.

**Comment by patataofcourse** [comment]
This has happened in one instance to one thief, while for the other doors work normally

**Comment by patataofcourse** [comment]
...for another user, the RPC doesn't seem to be going through

**Comment by Meorge** [comment]
From what I've seen it seems to come and go. I wonder if maybe it has to do with the user load (since there aren't many people playing right now it's able to work properly?)

**Comment by Meorge** [comment]
I think I may have done something to fix this? gonna close for now
