### ISSUE TITLE
Gemstone dissapears

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#31]
I got a gemstone while playing in two separate windows in the 0.1.6 alpha build (Windows), the gemstone suddenly dissapeared, I don't know when, but probably right when I got it. The gemstone kept appearing in the Eye's map but followed the cursor.
This error also appeared a couple of times:
![imagen](https://user-images.githubusercontent.com/29714419/64818469-69f0f100-d5ac-11e9-97d4-cbcd883b0502.png)

**Comment by Meorge** [comment]
Closing since I haven't seen this happen and a lot has changed since September 2019
