### ISSUE TITLE
Fix text problems in Spanish

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#32]
In both of these images, the text gets split in two lines. For this one, the text can be changed to "Unirse a un equipo":
![imagen](https://user-images.githubusercontent.com/29714419/64821311-d4a52b00-d5b2-11e9-87e7-bfccb3cfa3dd.png)
But for this one, maybe the text should be allowed to be a bit wider?
![imagen](https://user-images.githubusercontent.com/29714419/64821266-b4756c00-d5b2-11e9-84f9-542f7072560a.png)

**Comment by Meorge** [comment]
The "text splitting across lines" bug and the translation change have been fixed for v0.1.7
