### ISSUE TITLE
Kicked out of room, and unable to connect to server

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#39]
I was a thief in the 0.1.7 prealpha. I got caught. Suddenly I found myself on the title screen with this weird yellow lighting and stuck in the "connecting to server" loading screen

**Comment by patataofcourse** [comment]
Happened again when quitting as an Eye, may be a global issue

**Comment by Meorge** [comment]
Any errors in the log?

**Comment by patataofcourse** [comment]
...sorry, I reset. But it seems to happen every time I leave, and it sometimes stops connecting to the server when I press the "return to main menu" button

**Comment by Meorge** [comment]
The "return to main menu" modal bug has been fixed. I'm still unsure what you mean by yellow lighting

**Comment by patataofcourse** [comment]
I meant the kind of lightning that appears when being followed by a guard

**Comment by Meorge** [comment]
Haven't seen this issue pop up and a lot has changed since September 2019 so I'm closing this for now
