### ISSUE TITLE
Got busted through a door

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#43]
For some reason, a guard caught me through a closed door, and I was suddenly locked in place, then greeted with the "Busted" text

**Comment by Meorge** [comment]
I definitely know why this is happening - the hitbox for being caught simply didn't respect the solid wall between you. This might be a bit of work to fix

**Comment by Meorge** [comment]
This _should_ be fixed in v0.1.9. We can re-open the issue if it turns out to still be present.
