### ISSUE TITLE
Allow players to set their own color, instead of assigning it on a per-room basis

### ISSUE THREAD

**Issue by Meorge** [Meorge/sneaksters-testing#51]
People have said they'd like to be able to keep a certain color. I'm not _sure_ this is the best idea, since the way colors were assigned previously was done to help players be differentiated, and letting players pick their color before they enter a session means there could be players with the same color.

**Comment by patataofcourse** [comment]
Maybe it could be a "color preference", and if someone else already has it, the nearest color to the one selected is used?

**Comment by Meorge** [comment]
Something else that occurred to me - we'll have to figure out how to get this to work with color-blindness modes...

**Comment by Meorge** [comment]
Currently, thieves can set their color as a hex color code. Duplicates of the same color simply have the same color - there’s no sorting/auto color changing.
Soon I’ll hopefully be able to set up a friendlier UI for color selection.

**Comment by Meorge** [comment]
Going to open a new issue for a future version.
