### ISSUE TITLE
Better colors

### ISSUE THREAD

**Issue by RaspberryPiFan** [Meorge/sneaksters-testing#64]
https://github.com/Meorge/sneaksters-testing/blob/cff4d9d703e74f2fcc4bff27fb86252ff48a06ea/strings_en.json#L75

In my opinion it would be better if you set the coler in the game's code to white and the the color of `Eye in the Sky` to its current color. Not so important, just a little improvement.

**Comment by Meorge** [comment]
That makes a lot of sense. Those strings aren't actually being used in the game right now, though, so they may be removed in a future version.
