### ISSUE TITLE
Sometimes when someone joins the game, two players exist

### ISSUE THREAD

**Issue by brickblock369** [Meorge/sneaksters-testing#66]
![](https://cdn.discordapp.com/attachments/619932720621158402/658439841427619841/2.png)

Sometimes two identical players exist when someone joins the game. One is playable by the player, and the other is not movable in-game.

I wonder if it has to do with the games AFTER the first game?

**Comment by Meorge** [comment]
Was this only on the lobby screen, or in gameplay as well? It sounds like it happened after a gameplay session was completed?

**Comment by brickblock369** [comment]
Gameplay as well. Again, during the game, one is playable by the player, and the other is not movable in-game.

To answer "It sounds like it happened after a gameplay session was completed?", I really don't even know if that's the reason :/

**Comment by Meorge** [comment]
It would be nice to know that information so I can trace it back and find out what went wrong. I’d appreciate more detailed info about what happened/how many games had been played/etc if it happens again (error logs would also be helpful)

**Comment by Meorge** [comment]
Squad screen was redesigned to avoid these issues
