### ISSUE TITLE
Gem clips through the gift box

### ISSUE THREAD

**Issue by brickblock369** [Meorge/sneaksters-testing#68]
Sometimes the gem clips through the gift box. I don't think I'm even supposed to see the gem inside the box.

Perhaps it's unnecessary to load the gem graphics if we're supposed to carry gift boxes.

**Comment by Meorge** [comment]
Only one gem appearance should be active at a time. My guess is that it’s encountering an error while applying the gem appearance and this not hiding all but one of the models... will look more into this soon.

**Comment by Meorge** [comment]
It should be set up now so that it'll be only the gem if anything bad happens.
