### ISSUE TITLE
Mouse cursor doesn't affect some buttons

### ISSUE THREAD

**Issue by brickblock369** [Meorge/sneaksters-testing#69]
Some buttons don't do anything when I hover the mouse over them.

Selecting mission:
Buttons of mission 1, 2, and 3 do not get affected when I hover over them.

During the game:
The menu (accessed by Tab key)'s buttons as well.

The buttons don't change anything when I **click** on them as well.

**Comment by Meorge** [comment]
Those buttons may not be set to change color significantly when hovering over them. Are you sure you tried clicking all of them, and that nothing happened? The Pause menu's buttons do work for me when clicking them.

**Comment by brickblock369** [comment]
Yeah, I clicked missions 1, 2, and 3, and it didn't direct to the mission. Only mission 4 and 5 did.

**Comment by Meorge** [comment]
It would be helpful to have information on any errors that might pop up when you click on the mission buttons and nothing happens.

**Comment by Meorge** [comment]
I'm pretty sure this has been fixed with the most recent update (menus are navigated with controller or WASD, some of them work with buttons as well I think?)
