### ISSUE TITLE
Credits text

### ISSUE THREAD

**Issue by thomasdowding** [Meorge/sneaksters-testing#72]
On the credits screen, it is possible to scroll the names up and down using the mouse. This isn't really a major issue, just a weird thing I noticed that's probably not supposed to be there.

**Comment by Meorge** [comment]
Does the scrolling occur if you drag with the mouse, or use the scroll wheel?
Chances are this’ll be a pretty easy fix, just need to temporarily disable the scroll rect behavior while in credits mode.

**Comment by thomasdowding** [comment]
It's just with the mouse, the scroll wheel doesn't scroll it.

**Comment by Meorge** [comment]
Fixed in v0.2.1
