### ISSUE TITLE
Title screen

### ISSUE THREAD

**Issue by thomasdowding** [Meorge/sneaksters-testing#73]
On the title screen, the player has to click "back" to get onto the main menu. This could easily confuse a lot of people. "Start" would be better text to have there.

**Comment by Meorge** [comment]
Although there’s no button prompt, you’re supposed to press the Enter key on keyboards or the South button on controllers. I should make the back button hidden on the title screen.

**Comment by Meorge** [comment]
Implemented in v0.2.1
