### ISSUE TITLE
Error with displaying emotes

### ISSUE THREAD

**Issue by brickblock369** [Meorge/sneaksters-testing#77]
![이미지 1](https://user-images.githubusercontent.com/59150779/71427012-b34ee300-2667-11ea-8a03-872be6c611f5.png)

When I started up the game and started a mission the second time, I didn't see the emotes on the bottom-left specifying anything. When I started a mission the first and third time, it successfully specified the emotes. I wonder if the chance to do that is random?

Error log only said
``
WARNING: Shader Unsupported: 'Hidden/PostProcessing/Uber' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/PostProcessing/Uber' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/PostProcessing/FinalPass' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/PostProcessing/FinalPass' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Unlit/UI-Halftone' - Pass '' has no vertex shader
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'Unlit/UI-Halftone' - Setting to default shader.
``
Only things about shaders.

Windows

**Comment by Meorge** [comment]
That looks like the second page of emotes. You can toggle between the two pages by using the Left Trigger(?) on controllers or the Q key(?) on keyboards. (I'm not 100% certain on those, but they should be close.) I think I only ever made 5 emotes for the Thieves, so as a result "Bepis" takes up the whole second set.
