### ISSUE TITLE
Translations of "DANGER!"

### ISSUE THREAD

**Issue by Meorge** [Meorge/sneaksters-testing#79]
Please post here the translation for "DANGER!" (on the tape that shows up when a guard is chasing you) for your localization of Sneaksters.

**Comment by brickblock369** [comment]
Korean: 위험!

**Comment by NokNokShell** [comment]
Polish: UWAGA!

**Comment by RaspberryPiFan** [comment]
German: `GEFAHR!`

**Comment by RedStoneMatt** [comment]
French: "DANGER!" (yes it's the same as english)

**Comment by Meorge** [comment]
I think all of the translations are implemented now. Thanks everyone!

**Comment by patataofcourse** [comment]
You probably already have it, but in Spanish it's "¡Peligro!"

**Comment by patataofcourse** [comment]
thanks gmail

>
