### ISSUE TITLE
[Request-ish] Make a new build?

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#98]
The last testing build was made on Dec 31 2019, and expired a long while ago. Since progress for Sneaksters is continuing, would it be possible for a second Pre-Alpha 0.2.1 build to be made? It doesn't even need to add any changes after that point, honestly, I just want to be able to try out the game again, as I'm sure many other fans do.

Either way, thanks for continuing on this project and I hope many people can enjoy the hilarious and chaotic experience that playing Sneaksters with friends is!

**Comment by Meorge** [comment]
The current Sneaksters code is currently in the middle of being improved/changed. I think the next release will be v0.3.0, but there won't be any major user-side changes. v0.3.0 will be mostly just performance improvements and completing the switch to FMOD. Barring big unexpected issues, I would expect it to release in the next week or two.
